### ISSUE TITLE
NullPointerException in EntityEventJS.entityOf

### ISSUE THREAD

**Issue by evhub** [KubeJS-Mods/KubeJS#79]
I'm not exactly sure whether this is an error with KubeJS, with the KubeJS scripts I'm using, or with another mod, but the null pointer exception is coming from KubeJS code, so it seems most likely that the source of the error is there. [Here](https://gist.github.com/evhub/cc1b8bfc107402a92e07df6a252343b3) is the crash report. I'm using KubeJS 1605.3.6-build.160 on Forge 36.0.13 and Minecraft 1.16.5.

**Comment by SonicSpeedster16** [comment]
One of the players on my server encountered what appears to be the same crash last night.

Minecraft 1.16.5
Forge 36.0.14
kubejs-1605.3.6-build.160-forge
Direwolf20 pack v1.6.1

Crash Log: https://pastebin.com/1tZERZEx

**Comment by Vaelzan** [comment]
I mentioned this crash on Discord, but it makes sense for me to put it here too just to get a record of it on GitHub (since Discord messages tend to get lost over time)... there are a few different paths that can lead to a crash in the same place, as reported by a couple of other people:

This one should be fixed in a recent commit: https://gnomebot.dev/api/guild/file/303440391124942858/303440391124942858/819038479904276530/crash-2021-03-09_20.11.11-client.txt

But this one appears to still be triggerable (at a glance anyway):
https://gnomebot.dev/api/guild/file/303440391124942858/615627049637380144/817874337944043550/crash-2021-03-06_22.35.22-client.txt

**Comment by MaxNeedsSnacks** [comment]
Should hopefully all be fixed in the latest build!

**Comment by pabloliu** [comment]
I'm still having this bug caused by minecraft:bat in the latest build (kubejs-1605.3.6-build.176)

Crash report: https://pastebin.com/whUe6Fmh

**Comment by Vaelzan** [comment]
I figured I'd provide another crash report, this time from a client + server that are running Valhelsia 3, updated to the most recent build of KubeJS, and removed the Performant mod as a test (since I had seen it mentioned in some conversations). Different event triggering it to the previous comment.

https://pastebin.com/rhwR7kav
