### ISSUE TITLE
FoodBuilder is broken

### ISSUE THREAD

**Issue by Nyxane** [KubeJS-Mods/KubeJS#943]
### Minecraft Version

1.21.1

### KubeJS Version

2101.7.1-build.181

### Rhino Version

2101.2.6-build.66

### Architectury Version

-

### Forge/Fabric Version

Neoforge 21.1.107

### Describe your issue

Using the following Startup script, FoodBuilder(FoodProperties) does not yield the same FoodProperties
Notable effects:
Saturation gets set to (Nutrition * Saturation * 2) from FoodConstant.saturationByModifier
usingConvertsTo never gets initialized and is, null crashing the instance
```js
ItemEvents.modification((event) => {
    const $FoodBuilder = Java.loadClass("dev.latvian.mods.kubejs.item.FoodBuilder");
    event.modify("*", (item) => {
        if (item.get("food")) {
            console.log(item.get("food"))
            console.log($FoodBuilder(item.get("food")).build())
        }
    });
  });
```
https://github.com/KubeJS-Mods/KubeJS/blob/9205ad70f3e2d317cb0b3723556f7b2a055b782a/src/main/java/dev/latvian/mods/kubejs/item/FoodBuilder.java#L122-L124
https://github.com/KubeJS-Mods/KubeJS/blob/9205ad70f3e2d317cb0b3723556f7b2a055b782a/src/main/java/dev/latvian/mods/kubejs/item/FoodBuilder.java#L39-L46

**Comment by pietro-lopes** [comment]
That should be deprecated, currently KubeJS/Rhino can typewrap records like the FoodProperties is

just use `[]`

like
```js
ItemEvents.modification(event => {
  event.modify("*", item => {
    let originalFood = item.get("food")
    if (originalFood) {
      console.log(originalFood)
      item.setFood(
        [originalFood.nutrition(),
          originalFood.saturation(),
          originalFood.canAlwaysEat(),
          originalFood.eatSeconds(),
          originalFood.usingConvertsTo(),
          originalFood.effects()
        ])
    }
    let newFood = item.get("food")
    console.log(newFood)
  })
})
```

Btw @LatvianModder 
```
[03:27:02] [Render thread/INFO] [KubeJS Startup/]: FoodProperties[nutrition=9, saturation=21.6, canAlwaysEat=false, eatSeconds=1.6, usingConvertsTo=Optional.empty, effects=[]] [net.minecraft.world.food.FoodProperties]
[03:27:02] [Render thread/INFO] [KubeJS Startup/]: ItemModifications[item=pamhc2foodextended:tomatosoupitem] [dev.latvian.mods.kubejs.item.ItemModificationKubeEvent$ItemModifications]
[03:27:02] [Render thread/INFO] [KubeJS Startup/]: FoodProperties[nutrition=9, saturation=21.6, canAlwaysEat=false, eatSeconds=1.6, usingConvertsTo=Optional[0 minecraft:air], effects=[]] [net.minecraft.world.food.FoodProperties]
```
is this `Optional.empty` -> `Optional[0 minecraft:air]` fine? 💀

**Comment by wolfieboy09** [comment]
`Optional[0 minecraft:air]` is going to cause Minecraft to crash because it can't be empty (or 0)

**Comment by MaxNeedsSnacks** [comment]
Closing as I think I fixed this wrapper in 7.2? Feel free to reopen if not.

**Comment by BigJMoney** [comment]
@MaxNeedsSnacks I don't have permission to reopen, but here is my latest finding on 7.2-build.374:

This still appears reproducible in current KubeJS 1.21.1. The `usingConvertsTo` issue seems fixed, but saturation is still changed when an existing food is passed through `modifyFood()`.

Minimal repro:

```js
ItemEvents.modification(event => {
  event.modify('minecraft:mushroom_stew', item => {
    item.modifyFood(food => {
      food.alwaysEdible()
    })
  })
})
```

Vanilla mushroom stew has 6 nutrition and 7.2 saturation. After this modification, saturation effectively becomes 86.4 and therefore fills the player's saturation bar.

The culprit appears to be this line in `FoodBuilder(FoodProperties)`:

```java
this.saturation = properties.saturation();
```

`properties.saturation()` is already the final saturation value (7.2 for mushroom stew), but `FoodBuilder.build()` later treats `this.saturation` as a saturation **modifier** and passes it through `FoodConstants.saturationByModifier(...)` again.

Explicitly adding `food.saturation(0.6)` works around the issue.

So #943 looks only partially fixed: bowl conversion now appears to work correctly, but the saturation-copy issue remains.
